import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body>
        <p className='my-10'>Navbar</p>
        <main className='w-11/12 mx-auto'>{children}</main>
        <p className='my-10'>Footer</p>
      </body>
    </html>
  )
}
